- name: download nagios nrpe tarball
  sudo: true
  get_url: >
    dest={{nagios_build_directory}}
    url={{nagios_nrpe_tarball}}
    sha256sum={{nagios_nrpe_tarball_sha256sum}}

- name: untar the tarball
  sudo: true
  command: "tar -xvf nrpe-{{nagios_nrpe_version}}.tar.gz chdir={{nagios_build_directory}}"

- name: configure
  sudo: true
  command: "./configure --with-ssl=/usr/bin/openssl --with-ssl-lib={{nagios_ssl_lib_path}} chdir={{nagios_build_directory}}/nrpe-{{nagios_nrpe_version}}"

- name: make
  sudo: true
  command: "make all chdir={{nagios_build_directory}}/nrpe-{{nagios_nrpe_version}}"

- name: install nagios nrpe package
  sudo: true
  command: "checkinstall --pkgname=nrpe --requires='perl,libc6' --default chdir={{nagios_build_directory}}/nrpe-{{nagios_nrpe_version}}"
