---

- include: install.yml

- include: server.yml
  when: not redis_sentinel
  tags:
    - conf_update

- include: sentinel.yml
  when: redis_sentinel
  tags:
    - conf_update

- include: env_var.yml