---
- name: Install needed packages --> nagios-plugins, nagios-nrpe-server, percona nagios plugins
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - nagios-plugins
    - nagios-nrpe-server
    - libredis-perl

- name: Fetch device list from monit if availble? bydefault nagios will monitor /dev/xvda1
  set_fact: nagios_disk_monit=" {% if monit_disk_list is defined %}{{ monit_disk_list }} {% else %} '/dev/xvda' {% endif %}"

- debug: var=nagios_disk_monit

- name: Copy NRPE conf file
  template:
    src: templates/nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    mode: 0755

- name: Add local ip to allowed_hosts on /etc/nagios/nrpe.cfg
  lineinfile: dest=/etc/nagios/nrpe.cfg regexp='^allowed_hosts.*' line='allowed_hosts=127.0.0.1,{{ nagios_server_ip }}' state=present
  notify: 
  - restart nagios nrpe

# - name: Comment default hardcoded commands present inside nrpe.cfg
#   replace: dest=/etc/nagios/nrpe.cfg regexp='^command\[' replace='# \g<0>'

# - name: Give sudo passwordless to nagios
#   template: src=../templates/sudoers.j2 dest=/etc/sudoers.d/{{ username }} owner=root
#     group=root mode=0440 validate='visudo -cf %s'


- name: Copy alertmanager config parts
  copy:
    src: "{{item}}"
    dest: "/usr/lib/nagios/plugins/"
    mode: 0755
  with_fileglob:
    - files/plugins/*

- template:
    src: templates/nrpe_local.cfg.j2
    dest: /etc/nagios/nrpe_local.cfg
  notify: restart nagios nrpe
  changed_when: true
