---

#- debug: msg="Starting master server setup"
#  notify: restart postgresql
#  changed_when: true
#- meta: flush_handlers

- name: restart postgresql
  service:
    name: "postgresql-{{postgres_version}}"
    state: restarted
  when: ansible_os_family == "RedHat"
  
- name: restart postgresql
  service:
    name: "postgresql"
    state: restarted
  when: ansible_os_family == "Debian"


#Change postgres user password
- postgresql_user: name=postgres password="{{ pgsql.secret.postgres_password }}" encrypted=true
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

#- name: add user with superuser role
#  postgresql_user:
#    name: "{{pgsql.secret.username}}"
#    password: "{{pgsql.secret.password}}"
#    role_attr_flags: SUPERUSER
#  become: true
#  become_method: sudo
#  become_user: postgres


#pg_hba.conf for slave+pgpool server to connect to master
- template: src=templates/master_pg_hba.conf.j2 dest=/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
  when: ansible_os_family == "Debian"
  changed_when: true
  notify: debian-restart-postgresql
  
- name: Set pg_hba configuration file for RedHat family
  template: src=templates/master_pg_hba.conf.j2 dest="/var/lib/pgsql/{{ postgres_version}}/data/pg_hba.conf"
  when: ansible_os_family == "RedHat"
  changed_when: true
  notify: rhel-restart-postgresql

- meta: flush_handlers

